/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        gold: {
          50: '#fdf8e8',
          100: '#f5e8c8',
          200: '#e8d5a3',
          300: '#d4be6e',
          400: '#c9a84c',
          500: '#b8942e',
          600: '#8b6914',
          700: '#6b5010',
          800: '#4a380c',
          900: '#2a2008',
          950: '#1a1208',
        },
        rose: {
          50: '#fff5f8',
          100: '#fde8ef',
          200: '#f5b8cc',
          300: '#e8739a',
          400: '#d44a78',
          500: '#b83560',
          600: '#5c1f38',
          700: '#3d1526',
          800: '#2d0f1c',
          900: '#1a0810',
        },
        emerald: {
          50: '#f0fdf5',
          100: '#dcf5e8',
          200: '#a8f0cc',
          300: '#3dd68c',
          400: '#1db86e',
          500: '#0d8a52',
          600: '#0d4a22',
          700: '#072816',
          800: '#041a0e',
          900: '#020d08',
        },
        ivory: {
          50: '#fffef9',
          100: '#faf6ec',
          200: '#f0e8d5',
          300: '#e5ddc8',
          400: '#ece5d5',
          500: '#ddd3ba',
          600: '#c9b896',
          700: '#8b6914',
          800: '#4a380c',
          900: '#2a1f0a',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        heading: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        cormorant: ['Georgia', 'Times New Roman', 'serif'],
        lato: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        cinzel: ['Georgia', 'Times New Roman', 'serif'],
      },
      fontSize: {
        h1: ['var(--text-h1)', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['var(--text-h2)', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h3: ['var(--text-h3)', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '600' }],
        h4: ['var(--text-h4)', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '600' }],
        h5: ['var(--text-h5)', { lineHeight: '1.35', letterSpacing: '-0.02em', fontWeight: '600' }],
        body: ['var(--text-body)', { lineHeight: '1.6', fontWeight: '400' }],
        secondary: ['var(--text-secondary)', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['var(--text-secondary)', { lineHeight: '1.55' }],
        small: ['var(--text-small)', { lineHeight: '1.45' }],
        caption: ['var(--text-caption)', { lineHeight: '1.4' }],
      },
      letterSpacing: {
        tight: 'var(--tracking-tight)',
        eyebrow: 'var(--tracking-eyebrow)',
        heading: 'var(--tracking-tight)',
        'heading-tight': 'var(--tracking-tight)',
        display: 'var(--tracking-tight)',
      },
      lineHeight: {
        body: 'var(--leading-body)',
        heading: 'var(--leading-heading)',
        'heading-relaxed': 'var(--leading-heading-tight)',
        snug: 'var(--leading-snug)',
      },
      animation: {
        'float-gently': 'floatGently 3s ease-in-out infinite',
        'wave': 'wave 0.8s ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
        'confetti-fall': 'confettiFall 3s ease-in forwards',
        'bg-pulse': 'bgPulse 6s ease-in-out infinite alternate',
      },
      keyframes: {
        floatGently: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        wave: {
          '0%, 100%': { transform: 'scaleY(1)', opacity: '0.3' },
          '50%': { transform: 'scaleY(1.6)', opacity: '1' },
        },
        confettiFall: {
          '0%': { transform: 'translateY(-20px) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(110vh) rotate(720deg)', opacity: '0' },
        },
        bgPulse: {
          'from': { opacity: '0.2', transform: 'scale(1)' },
          'to': { opacity: '0.6', transform: 'scale(1.05)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
